name: Build DWMBlurGlass

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore: ["**.md"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout DWMBlurGlass
        uses: actions/checkout@v4

      - name: Checkout MiaoUILite
        uses: actions/checkout@v4
        with:
          repository: Maplespe/MiaoUILite
          path: deps/MiaoUILite

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore DWMBlurGlass.sln -NonInteractive

      - name: Build MiaoUILite (Release x64)
        run: >
          msbuild deps\MiaoUILite\MiaoUI\MiaoUI.vcxproj
          /m
          /p:Configuration=Release
          /p:Platform=x64
          /p:PreferredToolArchitecture=x64

      - name: Build DWMBlurGlass Release x64
        run: >
          msbuild DWMBlurGlass.sln
          /m
          /p:Configuration=Release
          /p:Platform=x64
          /p:PreferredToolArchitecture=x64
          /p:MUI_LITE_LIBRARY="${{ github.workspace }}\deps\MiaoUILite\MiaoUI"
          /p:AdditionalOptions="/utf-8"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DWMBlurGlass-x64-Release
          path: |
            Build/**
            Languagefiles/**
          if-no-files-found: error
